### ISSUE TITLE
3/22/18 1pm - Haskell Study Group - Meeting 1: Introduction - Deep Space Coffee

### ISSUE THREAD

**Issue by metame** [fpnm/fpabq#1]
The first meeting for the Haskell Study Group to go through the Haskell Book.  

Tentative location ( participants < 5 ): Deep Space Coffee, 504 Central Ave SW, Albuquerque, NM 87102
Time: 1pm - 3pm (we'll try to do the majority of it in the first hour for those who have limited lunch breaks)
Requirements: A computer and a paid-for copy of the Haskell Book (http://haskellbook.com/)

RSVP with a comment below

**Comment by TheEndIsNear** [comment]
Will be there for the first hour.

**Comment by StephenRansom** [comment]
12:30 is a little bit better than 1:00 for me, but not crucial. I have standup at 2:00 so I'll be leaving a bit early either way.

**Comment by mtice** [comment]
I'm in. Probably just first hour also.. but down to show up a bit early with Stevie.

**Comment by metame** [comment]
I will be there at 1230 also and stay until at least 2.

**Comment by ctm** [comment]
I'll be there at 12:30. Not sure how long I can stay, but at least an hour.
