### ISSUE TITLE
04/05/18 12:30pm - Haskell Study Group - Meeting 2: Review Ch4-5 - Deep Space Coffee

### ISSUE THREAD

**Issue by mtice** [fpnm/fpabq#2]
Location: Deep Space Coffee, 504 Central Ave SW, Albuquerque, NM 87102

Time: 12:30pm - 2ish (we'll try to do the majority of it in the first hour for those who have limited lunch breaks)

Requirements: A computer and a paid-for copy of the Haskell Book (http://haskellbook.com/)

Topics:
Week one ended on 3.22 with meetup discussing ch 1. Following [this](https://github.com/sjsyrek/haskell-study-startup/blob/master/guidelines.md#schedule) schedule, this session will be review of chapters 4 and 5.

RSVP with comment below

EDIT: Updated ch 2-3 to 4-5. Thanks for the clarification of @ctm below

**Comment by ctm** [comment]
I thought we reviewed chapters 2 and 3 via Slack this most recent Thursday and that at our physical meeting at Deep Space we'd go over 4 and 5.

ETA: Oh, and I'll be there regardless, but I'm through chapter 5 already.

**Comment by mtice** [comment]
That's fine. I'm that far now. The schedule for week 3 just says "Review chapters 2-3" and "ch 4-5" for week 3. Since this is END of week 3, I guess we should be reviewing 4-5. I can change if that makes more sense to everyone.

**Comment by TheEndIsNear** [comment]
So, how I understood it was, you reread ch 2-3 to review it, and then go to ch 4-5.

**Comment by TheEndIsNear** [comment]
Also, I will be there.

**Comment by metame** [comment]
I will also be there
