### ISSUE TITLE
04/19/18 12:30pm - Haskell Study Group - Meeting 3: Review Ch7-8 - Deep Space Coffee #3

### ISSUE THREAD

**Issue by TheEndIsNear** [fpnm/fpabq#4]
Location: Deep Space Coffee, 504 Central Ave SW, Albuquerque, NM 87102

Time: 12:30pm - 2ish (we'll try to do the majority of it in the first hour for those who have limited lunch breaks)

Requirements: A computer and a paid-for copy of the Haskell Book (http://haskellbook.com/)

Topics:
Week two ended on 4.05 with meetup discussing chapters 4 and 5. Following this schedule, this session will be review of chapters 7 and 8. 

RSVP with comment below

**Comment by metame** [comment]
I will be there 😄

**Comment by ctm** [comment]
I'll be there. So far, I've read both chapters except `8.7 Definitions`. I've done all the exercises I've come across so far. I expect to read 8.7 sometime today.

**Comment by ctm** [comment]
Ha! 8.7 was ridiculously short. The Definitions portion of chapter 7 was a bit time consuming for me due to me not immediately understanding how their point-free examples worked. As such, I expected the Definitions portion of chapter 8 to be even more time consuming. Again, ha!
