### ISSUE TITLE
05/03/18 12:30pm - Haskell Study Group - Meeting 4?: Review Ch11-12 - RSI Basement

### ISSUE THREAD

**Issue by mtice** [fpnm/fpabq#5]
Location: RSI Basement 723 Silver sw 87102
Time: 4pm - 6pm, 05/03/2018

Requirements: A computer and a paid-for copy of the Haskell Book (http://haskellbook.com/)

Topics:
Discussion of ch 11-12. Go through some exercises together. Use whiteboard for something. Discuss catch up week.

RSVP with comment below

**Comment by TheEndIsNear** [comment]
Will be there

**Comment by ctm** [comment]
I'll be there.
