### ISSUE TITLE
05/31/18 12:30pm - Haskell Study Group - Meeting 5?: Catch up. - RSI Basement

### ISSUE THREAD

**Issue by mtice** [fpnm/fpabq#6]
Location: RSI Basement 723 Silver sw 87102
Time: 4pm - 6pm, 05/03/2018

Requirements: A computer and a paid-for copy of the Haskell Book (http://haskellbook.com/)

Topics:
Catch up. Some are on ch16, some a bit less. Let's get on the same page and go through some more exercises together. Also talk about post meeting plans.

RSVP with comment below

**Comment by ctm** [comment]
I'll be there! I'm also bringing my pool cue so we can head over to Anodyne, after.

**Comment by TheEndIsNear** [comment]
Will be there.

**Comment by metame** [comment]
As will I

**Comment by ctm** [comment]
I'm in the south lobby. How do I get in?

**Comment by mtice** [comment]
I'm outside sw corner.

**Comment by mtice** [comment]
723 silver sw?

**Comment by ctm** [comment]
I walked out to sw corner and didn't see anyone. I must have gotten your message too late.

**Comment by ctm** [comment]
Maybe not. I may be in the wrong building. I'll walk further. Sorry about this.

**Comment by mtice** [comment]
I'll keep an eye on it.
